### ISSUE TITLE
Convert examples to `.robot` format

### ISSUE THREAD

**Issue by pekkaklarck** [daluu/robotframework-simple-page-object-example#1]
Great to have another Robot Framework example! Unfortunately the HTML files cannot be opened directly from GitHub. Have you considered converting them to use the plain text format and the `.robot` extension? That way GitHub would highlight them directly. See this file for an example:
https://github.com/robotframework/robotframework/blob/master/atest/testdata/misc/pass_and_fail.robot

Converting the format is very easy with Robot's built-in Tidy tool:

```
python -m robot.tidy tests.html tests.robot
```

Tidy's output ought to be pretty good, but you can obviously reformat tests afterwards if needed.

**Comment by daluu** [comment]
Done, and HTML versions can be viewed from the Github.io pages:

http://daluu.github.io/robotframework-simple-page-object-example/PageObjectExampleTest.html
http://daluu.github.io/robotframework-simple-page-object-example/GoogleSearchPage.html

and the home page sort of serves as an alternate readme: http://daluu.github.io/robotframework-simple-page-object-example/

**Comment by daluu** [comment]
I forgot about this nifty tool earlier. For HTML version, it's rendered output can be viewed like this as well:

http://htmlpreview.github.io/?https://github.com/daluu/robotframework-simple-page-object-example/blob/master/PageObjectExampleTest.html

http://htmlpreview.github.io/?https://github.com/daluu/robotframework-simple-page-object-example/blob/master/GoogleSearchPage.html

**Comment by pekkaklarck** [comment]
Great, thanks! Personally I would just keep the *.robot files and remove *.html versions altogether, though.
